name = "yakei-platform"
compatibility_date = "2024-01-01"
account_id = "7d83eb84684ddc7adec64a72505f69f0"

[[r2_buckets]]
binding = "VIDEOS_BUCKET"
bucket_name = "yakei-videos"

[vars]
ENVIRONMENT = "development"
